version: '3.7'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
    pull_policy: always
    tty: true
    restart: always
    #environment:
    #  - OLLAMA_DEBUG=1
    entrypoint: ["/usr/bin/bash", "/custom-entrypoint.sh"]

  vector-db:
    image: semitechnologies/weaviate:latest
    container_name: vector-db
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/
      - WEAVIATE_SINGLE_NODE=true
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always

  app:
    build: ./app
    container_name: app
    depends_on:
      - vector-db
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    volumes:
      - ${DATA_VOLUME:-./data}:/data

volumes:
  weaviate_data:
    external: false
