version: '3.8'

services:
  app:
    build:
      context: ./app
    volumes:
      - ${DATA_VOLUME:-./data}:/data
    depends_on:
      - vector-db
    command: python3 main.py

  vector-db:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
